story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from story9 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mypage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('formPage/', include('story5.urls')),
    path('kegiatan/',include('story6.urls')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('register/',v.register, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.tambahKegiatan, name='kegiatan'),
    path('data/', views.dataKegiatan, name='dataKegiatan'),
    # dilanjutkan ...
]

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    kegiatan = models.CharField('Kegiatan', max_length=100, null=True, blank=False)

    class Meta:
        db_table = 'kegiatan'

    def __str__(self):
        return str(self.kegiatan)


class Pendaftar(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    nama = models.CharField('Pendaftar', max_length=50, null=True, blank=False)

    class Meta:
        db_table = 'pendaftar'

    def __str__(self):
        return str(self.nama)

story6/forms.py
from django.forms import ModelForm
from .models import Kegiatan, Pendaftar

class KegiatanForm(ModelForm):
    required_css_class = 'required'

    class Meta :
        model = Kegiatan
        fields = '__all__'   

class PendaftarForm(ModelForm):
    required_css_class = 'required'

    class Meta :
        model = Pendaftar
        fields = '__all__'   

story6/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from story6.models import Kegiatan, Pendaftar
from story6.forms import KegiatanForm, PendaftarForm
# Create your views here.

def kegiatan(request):
    return render(request,'kegiatan.html')

# Create your views here.
def tambahKegiatan(request):
    data_kegiatan_list = Kegiatan.objects.all()
    form = KegiatanForm()
    if request.method == 'POST':
        forminput = KegiatanForm(request.POST)
        if forminput.is_valid():
            forminput.save()
            return render(request, 'kegiatan.html', {'form':form, 'status': 'success', 'data' : data_kegiatan_list})
        else:
            return render(request, 'kegiatan.html', {'form':form, 'status': 'failed', 'data' : data_kegiatan_list})
            
    else: #Kalo method GET
        current_data = Kegiatan.objects.all()
        return render(request, 'kegiatan.html', {'form':form, 'data':current_data})

def dataKegiatan(request):
    form = PendaftarForm()
    data_kegiatan_list = Kegiatan.objects.all()
    data_pendaftar_list = Pendaftar.objects.all()
    if request.method == 'POST':
        forminput = PendaftarForm(request.POST)
        if forminput.is_valid():
            forminput.save()
            return redirect('story6:dataKegiatan')
        else:
            dataPendaftar = Pendaftar.objects.all()
            return render(request, 'dataKegiatan.html', {'form':form, 'status': 'failed', 'dataPendaftar' : data_pendaftar_list, 'dataKegiatan': data_kegiatan_list,})
    else:
        return render(request,'dataKegiatan.html', {'form':form, 'status': 'failed', 'dataPendaftar' : data_pendaftar_list, 'dataKegiatan': data_kegiatan_list})

story6/templates/dataKegiatan.html
<!DOCTYPE html>
<head>
    <div class="main">
        <h3 class="title" style="margin-top:4vw;">list <span>jadwal</span></h3>
        <div class="button" style="margin: 4vw;">
          <a href="{% url 'story6:kegiatan' %}" class="btn btn-outline-primary" role="button" aria-pressed="true">Isi jadwal</a>  
        </div>
    </div>

    <style>
        * {
    box-sizing: border-box;
  }
  
  /* Float four columns side by side */
  .column {
    float: left;
    width: 25%;
    padding: 0 10px;
  }
  

  .row {margin: 0 -5px;}
  

  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  

  @media screen and (max-width: 700px) {
    .column {
      width: 100%;
      display: block;
      margin-bottom: 5vw;
    }
  }
  
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 2vw;
    text-align: center;
    background-color: #ffffff;
  }
  .card:hover {
      box-shadow: 0 8px 16px 0 #b31321;
  }

    </style>

</head>
<body>
    {% csrf_token %}
    {% for data in dataKegiatan %}
        <div class="container">
            <div class="column" style="margin-bottom: 1vw;">
                <div class="card">
                    <h3 class="title2" style="font-size: clamp(16px, 2vw, 37px);" ><span>{{data.kegiatan}}</span></h3>
                    {% csrf_token %}
                    {% for datap in dataPendaftar %}
                        {% if datap.kegiatan == data %}
                            <h1 style="font-size: clamp(12px, 1.5vw, 33px);"> {{datap.nama}} </h1>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
      </div>
    {% endfor %}

    <section class="container-fluid d-flex flex-wrap align-content-center">
        <div class="form" style="margin:5vw">
            <form action="" method="POST" novalidate>
            {% csrf_token %}
            <table class="table mx-3" style="width:88vw">
                {{ form.as_table }}
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
                </tr>
            </table>
            </form>
        </div>
    </section>
  
</body>
</html>
  

story6/templates/kegiatan.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tambah Kegiatan</title>
    </head>
    <body>{% block content %}
        <div class="intro">
            <div class="center" align="center">
                <h3 class="title" style="margin-top: 2vw;">Tambah <span><br>kegiatan</span></h3>
                    <a href="{% url 'story6:dataKegiatan' %}" class="btn btn-outline-primary" role="button" aria-pressed="true">Lihat Jadwal</a>  
                  </div>
            </div>
                {% if status %}
                    {% if status == 'success' %}
                    <div class="alert alert-success" role="alert">
                        Sukses menambahkan kegiatan baru
                    </div>
                    {% else %}
                    <div class="alert alert-danger" role="alert">
                        Terjadi kesalahan input, silahkan coba lagi
                    </div>
                    {% endif %}
                {% endif %}
                <section class="container-fluid d-flex flex-wrap align-content-center ">
                    <form action="" method="POST" novalidate>
                        {% csrf_token %}
                        <table class="table mx-3" style="width:88vw">
                            {{ form.as_table }}
                            <tr>
                                <td>&nbsp;</td>
                                <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
                            </tr>
                        </table>
                    </form>
            
            </section>
        </div>
        {% endblock content %}
        </body>
</html>