story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from story9 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mypage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('formPage/', include('story5.urls')),
    path('kegiatan/',include('story6.urls')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('register/',v.register, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story5/urls.py
from django.urls import path
from .views import Join, mtkul_delete

app_name = 'story5'

urlpatterns = [
    # path('formPage/',views.formPage,name='formPage'),
    path('',Join, name = 'formPage'),
    path('<int:pk>', mtkul_delete, name ='delete')
]

story5/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    nama_Matkul = models.CharField(max_length=50, null = True)
    dosen_Pengajar = models.CharField(max_length=50, null = True)
    jumlah_SKS = models.IntegerField(null = True)
    deskripsi = models.CharField(max_length=100)
    semester_Tahun = models.IntegerField(null = True)
    ruang_Kelas = models.CharField(max_length=50, null = True)

story5/forms.py
from django import forms

class MatkulForm(forms.Form):

    nama_Matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))

    dosen_Pengajar = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True,
    }))

    jumlah_SKS = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'Integer',
        'required' : True,
    }))

    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'placeholder' : 'deskripsi matkul',
        'required' : True,
    }))

    semester_Tahun = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'Integer',
        'placeholder' : 'Semester Tahun',
        'required' : True,
    }))

    ruang_Kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'placeholder' : 'Ruang Kelas',
        'required' : True,
    }))

story5/views.py
from django.shortcuts import render,redirect
from .models import Matkul as matkulz
from .forms import MatkulForm

# Create your views here.

def formPage(request):
    return render(request,'formPage.html')

def Join(request):
    if request.method == "POST":
        form  = MatkulForm(request.POST)
        if form.is_valid():
            mtkul = matkulz()
            mtkul.nama_Matkul = form.cleaned_data['nama_Matkul']
            mtkul.dosen_Pengajar = form.cleaned_data['dosen_Pengajar']
            mtkul.jumlah_SKS = form.cleaned_data['jumlah_SKS']
            mtkul.deskripsi = form.cleaned_data['deskripsi']
            mtkul.semester_Tahun = form.cleaned_data['semester_Tahun']
            mtkul.ruang_Kelas = form.cleaned_data['ruang_Kelas']
            mtkul.save()
        return redirect('/formPage')
    else:
        mtkul = matkulz.objects.all()
        form = MatkulForm()
        response = {'mtkul':mtkul, 'form':form}
        return render(request,'formPage.html',response)

def mtkul_delete(request,pk):
    if request.method == "POST":
        form  = MatkulForm(request.POST)
        if form.is_valid():
            mtkul = matkulz()
            mtkul.nama_Matkul = form.cleaned_data['nama_Matkul']
            mtkul.dosen_Pengajar = form.cleaned_data['dosen_Pengajar']
            mtkul.jumlah_SKS = form.cleaned_data['jumlah_SKS']
            mtkul.deskripsi = form.cleaned_data['deskripsi']
            mtkul.semester_Tahun = form.cleaned_data['semester_Tahun']
            mtkul.ruang_Kelas = form.cleaned_data['ruang_Kelas']
            mtkul.save()
        return redirect('/formPage')
    else:
        matkulz.objects.filter(pk=pk).delete()
        data = matkulz.objects.all()
        form = MatkulForm()
        response = {"mtkul":data, "form": form}
        return render(request,'formPage.html', response)
        

story5/templates/formPage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>
<div class="row">
    <div class="col-md-12" style="text-align: left;">
        <form action='' method="POST">
            {% csrf_token %}
            {{ form }}
            <div class="centre-items" style="margin-top: 50px; text-align: center;">
                <input type="submit" class="btn btn-primary" value="Add Form" style="margin-bottom: 50px;">
            </div>
        </form>
    </div>
    <div class="col" id="tulisan">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Mata Kuliah</th>
                <th scope="col">Dosen</th>
                <th scope="col">SKS</th>
                <th scope="col">Tahun</th>
                <th scope="col">Kelas</th>
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for matkulz in mtkul %}
                <tr>
                    <th scope="row">{{matkulz.nama_Matkul}}</th>
                    <td>{{matkulz.dosen_Pengajar}}</td>
                    <td>{{matkulz.jumlah_SKS}}</td>
                    <td>{{matkulz.deskripsi}}</td>
                    <td>{{matkulz.ruang_Kelas}}</td>
                    <td><a href="{% url 'story5:delete' pk=matkulz.pk %}"><button class="btn btn-icon btn-danger">Delete</button></a> </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

</body>
</html>