mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_me/', views.about_me, name='about_me'),
    path('skill/', views.skill, name='skill'),
    path('gallery/', views.gallery, name='gallery'),
    path('social_media/', views.social_media, name='social_media'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from story9 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mypage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('formPage/', include('story5.urls')),
    path('kegiatan/',include('story6.urls')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('register/',v.register, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mypage/models.py
from django.db import models

# Create your models here.

mypage/views.py
from django.shortcuts import render

# Create your views here.

def index(request): 
    return render(request,'home.html')

def about_me(request):
    return render(request, 'about_me_page.html')

def skill(request):
    return render(request, 'skill_page.html')

def gallery(request):
    return render(request, 'gallery.html')

def social_media(request):
    return render(request, 'socialmedia_page.html')

mypage/templates/about_me_page.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>About Me</title>
</head>
<body>
  <div class="background">
      <nav class="navbar">
        <a class="navbar-brand" href="#">
          <div class="judul">ABOUT ME</div>
        </a>
        
        <!-- <a href="{% url 'mypage:index' %}" class="home_box">HOME</a> -->
      </nav>
      <div class="line"></div>
      <div class="container" style="margin-left: -2em;">
        <div class="row">
          <div class="col-md-12">
            <div class="konten">Hai!, Perkenalkan nama saya adalah Muhammad Arsyanda Tjandra seperti yang di halaman pertama, saya adalah seorang mahasiswa di Universitas Indonesia dengan program studi ilmu komputer. Saya bercita-cita ingin menjadi seorang software engineer handal yang bisa membuat perubahan di dunia. Saya tamat SMA pada tahun 2019 dari SMA Islam Al - Azhar 1 Jakarta. Hobi saya adalah bermain game yaitu DOTA 2 dan saya juga sangat menyukai ngoding</div>
  
          </div>
          <div class="col-md-4">
            <img src="{% static 'dotalogo.png' %}" style="margin-left: 5em;">
          </div>
          <div class="col-md-4">
            <img src="{% static 'codinglogo.jpeg' %}" style="margin-left: 5em;" >
          </div>
        </div>
      </div>
  
  </div>
</body>

</html>

mypage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>Gallery</title>
</head>
<body>
  <div class="background">
      <nav class="navbar">
        <a class="navbar-brand" href="#">
          <div class="judul">Gallery</div>
        </a>
        <a href="{% url 'mypage:index' %}" class="home_box">HOME</a>
      </nav>
      <div class="line"></div>
      <div class="container" style="margin-top: 10em;">
        <div class="row">
          <div class="col-md-4">
            <img src="{% static 'IMG_4164.jpeg' %}">
          </div>
          <div class="col-md-4">
            <img src="{% static 'IMG_1801.jpeg' %}">
          </div>
          <div class="col-md-4">
            <img src="{% static 'IMG_3146.jpeg' %}">
          </div>
        </div>
      </div>
  
  </div>
</body>

</html>

mypage/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> 
    <title>Home</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    {% block content %}
    <div class="background">
      <div class="header header_phone">
        <nav class="navbar">
          <a class="navbar-brand" href="#">
            <img src="{% static 'v21_10.png' %}" class="logofasilkom phone">
          </a>
          <div class="kontak">📞 087700112510 || 📩 muhammad.arsyanda@ui.ac.id</div>
        </nav>
      </div>
      <div class="row">
        <div class="col-3 box_d">
          <a href="{% url 'mypage:gallery' %}"class="home font_size"> GALLERY</a>

        </div>
        <div class="col-3 box_d">
          <a href="{% url 'mypage:about_me' %}" class="home font_size">ABOUT ME</a>
        </div>
        <div class="col-3 box_d">
          <a href="{% url 'mypage:skill' %}" class="home font_size">SKILL</a>
        </div>
        <div class="col-3 box_d font_size">
          <a href="{% url 'mypage:social_media' %}" class="home font_size">SOCIAL MEDIA</a>
        </div>
        <div class="col-6">
          <img src="{% static 'v5_1.png' %}" class="profile_img img_phone">
        </div>
        <div class="col-6">
          <div class="introduction_box">introduction</div>
          <div class="page_content">Nama saya adalah Muhammad Arsyanda Tjandra, saya adalah seorang mahasiswa S1 di Universitas Indonesia jurusan ilmu komputer</div>
  
        </div>
      </div>
    </div>
    {% endblock %}
    {% else %}
    <p><a href="/login">Login</a></p>
    {% endif %}
  </body>

</html>

mypage/templates/skill_page.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>Skill</title>
</head>
<body>
  <div class="background">
      <nav class="navbar">
        <a class="navbar-brand" href="#">
          <div class="judul">SKILL</div>
        </a>
        <a href="{% url 'mypage:index' %}" class="home_box">HOME</a>
      </nav>
      <div class="line"></div>
      <div class="container" style="margin-left: -2em;">
        <div class="row">
          <div class="col-md-12">
            <div class="konten">Saya mempunyai beberapa skill yaitu : <br />- Mengerti bahasa pemrograman Python<br /> - Mengerti bahasa pemrograman Java <br />- Bisa ber-organisasi / bekerja sama dengan orang lain <br />- Bisa menggunakan Microsoft Office <br />- Bisa membuat website</div>
  
          </div>
          <div class="col-md-4">
            <img src="{% static 'javalogo.png' %}">
          </div>
          <div class="col-md-4">
            <img src="{% static 'pythonlogo.png' %}">
          </div>
          <div class="col-md-4">
            <img src="{% static 'djangologo.png' %}">
          </div>
        </div>
      </div>
  
  </div>
</body>

</html>

mypage/templates/socialmedia_page.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>Social Media</title>
</head>
<body>
  <div class="background">
      <nav class="navbar">
        <a class="navbar-brand" href="#">
          <div class="judul">Social media</div>
        </a>
        <a href="{% url 'mypage:index' %}" class="home_box">HOME</a>
      </nav>
      <div class="line"></div>
      <div class="container" style="margin-top: 10em;">
        <div class="row">
          <div class="col-md-4">
            <img src="{% static 'twitterlogo.png' %}">
            <div class="caption" style="margin-top: 2.5em;">@arsyandatj</div>
          </div>
          <div class="col-md-4">
            <img src="{% static 'instagramlogo.jpeg' %}">
            <div class="caption" style="margin-top: 3em;">@arsyandatj</div>
          </div>
          <div class="col-md-4">
            <img src="{% static 'spotifylogo.png' %}">
            <div class="caption" style="margin-top: 2em;">@arsyandatj</div>
          </div>
        </div>
      </div>
  
  </div>
</body>

</html>